### ISSUE TITLE
YouTube Returning 404 for get_video_info URL

### ISSUE THREAD

**Issue by alexckent** [MaisumAbbas/YouTube-Video-Downloader#1]
YouTube seems to have moved this URL...

https://www.youtube.com/get_video_info?video_id=JZTRYUCtF5c

Error message is:

Warning: file_get_contents(https://youtube.com/get_video_info?video_id=JZTRYUCtF5c): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found in /usr/share/youtube_downloader/class.youtube.php on line 30

**Comment by MaisumAbbas** [comment]
Please make sure the video you are trying to download is unlicensed. Videos which are licensed, you can't download those by such downloaders. @alexckent

**Comment by alexckent** [comment]
Have you got an example of a video where the URL returns anything other than a 404 page?
https://www.youtube.com/get_video_info?video_id=ON1mTU-fn8E

**Comment by MaisumAbbas** [comment]
You need to copy the URL shown in the address bar to download such as https://www.youtube.com/watch?v=LlaNSWRTaY0. This is a licensed one though. I can't seem to find any unlicensed videos unfortunately. I am not sure whether YouTube has updated something due to which I couldn't download a video or I am just unable to find an unlicensed one at the moment.

**Comment by alexckent** [comment]
Thanks for confirming the bug. It's not a problem with licensed or unlicensed videos, but a change in YouTube's get_video_info file that seems to have disappeared.
